### PR TITLE
Fix #62

### LINKED ISSUE #62: Flush DNS cache on add/remove DNS server
A workflow for a user using a VPN might go like this:

* Not connected to VPN
* Attempt to visit website
* systemd-resolved resolves website and caches result
* Find website is blocked by ISP
* Connect to VPN, using this script to get DNS servers from VPN
* Attempt to visit website again to avoid blocking

However, because systemd-resolved has cached the DNS request from the previous attempt, the visit to the website fails.

One can work around this manually by `systemd-resolved --flush-cache`

It seems more appropriate to invalidate the DNS cache every time this script adds/removes a DNS server so that systemd-resolved will attempt to resolve DNS requests with the newly provided VPN DNS servers when required.

Please have the script flush systemd-resolved DNS cache on every add/remove.

### PR DESCRIPTION
**Pull request by Edu4rdSHL**

### CODE REVIEW

**Comment by jonathanio** [comment]
@Edu4rdSHL Thanks for the pull-request. I'm going to merge this, although, once done I'm going to move the command until after the `"${script_type}" ...` call towards the end of the `main()` as that's what calls `up()` and `down()`, so it can be done in once place. Plus, by moving it until after that call, there is less chance of the race condition where possible DNS values are cached between the flushing of the caches and the full addition of the new DNS settings on the link.

**Comment by Edu4rdSHL** [comment]
Hello, @jonathanio you're totally right. Thanks for notify and do the re-work.

**Comment by jonathanio** [comment]
@Edu4rdSHL no problem. I in fact caught myself out having not run the tests with this refactor, but I've fixed the change and will release this (and a number of other changes) this afternoon.

Thanks again!

**Comment by Edu4rdSHL** [comment]
Very good, I was going to tell you about the release since that Im using the ArchLinux AUR package that use the versioned model.

Thank you for it excellent tool.

**Comment by jonathanio** [comment]
No problem. Once I've finished all the work on this I'll update the AUR package configuration and upload it there.

**Pull request merged**
