### PR TITLE
down-pre, not pre-down

### LINKED ISSUE #4: pre-down is an "Unrecognized option or missing parameter"
It looks like this was updated a couple days ago, so I may be doing something wrong with my configuration, but openvpn isn't recognizing pre-down as valid. It is (predictably) not a valid route-pre-down script, and a simple down fails out since tun0, as expected, does not exist. I could not find a mention of pre-down in the man pages anywhere.

I have not had much time to poke at the manual, but could we write a complementary route-pre-down to handle this?

OpenVPN 2.3.11
iproute2 4.7.0
systemd 231

### PR DESCRIPTION
**Pull request by pid1**
Fixes #4

### CODE REVIEW

**Comment by jonathanio** [comment]
@pid1: There will also need to be a change in `Makefile` as there's reference to the configuration option in there too? Would you be able to update that too, and then I'll merge and release. Thanks.

**Comment by pid1** [comment]
Updated. We should tag a release and update the AUR package as well.

**Comment by jonathanio** [comment]
That's no problem. Once I get home I'll update that package and put a new release out, although TBF none of these commits will change anything in the script itself. Probably the Wiki will need a change more importantly, and I might put out a message on install on how to configure it.

**Comment by pid1** [comment]
Updating the wiki now. Do we still need `setenv PATH /usr/bin`? I do not see why we are overriding that here.

**Comment by jonathanio** [comment]
I don't think so, especially on Arch as everything is symlinked to /use/bin anyway. I don't enable it and not had an issue.

**Comment by pid1** [comment]
Wiki is updated.

**Pull request merged**
